// Front-end Developer/quote-generator/src/components/Footer.tsx
const Footer = () => {
  return (
    <div className="mx-auto mb-6">
      <p className="text-gray-400 text-xs md:text-base">
        created by{" "}
        <a
          href="https://devchallenges.io/portfolio/siamtbhuiyan"
          className="font-bold"
        >
          @siamtbhuiyan
        </a>{" "}
        - devChallenges
      </p>
    </div>
  );
};

export default Footer;

// Front-end Developer/windbnb/src/components/Footer.vue
<script lang="ts">
import { defineComponent } from "vue";
export default defineComponent({});
</script>
<template>
  <div class="pt-12 text-gray-400 flex justify-center text-xs md:text-base">
    created by
    <a href="https://devchallenges.io/portfolio/siamtbhuiyan" class="font-bold"
      >@siamtbhuiyan</a
    >
    - devChallenges
  </div>
</template>
