// Front-end Developer/country-quiz/src/components/Footer.vue
<script setup></script>
<template>
  <div class="footer">
    created by
    <a
      href="https://github.com/siamtbhuiyan"
      class="font-bold px-1"
      target="_blank"
    >
      @siamtbhuiyan</a
    >
    -
    <a
      href="https://devchallenges.io/solutions/1qlSE0egxnFk3dntCZOp"
      class="px-1 cursor-pointer"
      target="_blank"
      >devChallenges</a
    >
  </div>
</template>

// Front-end Developer/search-jobs/src/components/Footer.jsx
const Footer = () => {
    return (
      <>
        <p className="text-gray-400 mx-auto pb-3 text-center text-xs sm:text-base">
          created by{" "}
          <a
            href="https://github.com/siamtbhuiyan"
            target="_blank"
            className="font-bold"
          >
            @siamtbhuiyan
          </a>{" "}
          - devChallenges
        </p>
      </>
    );
  };
  
  export default Footer;
