// Front-end Developer/windbnb/src/components/Footer.vue
<script lang="ts">
import { defineComponent } from "vue";
export default defineComponent({});
</script>
<template>
  <div class="pt-12 text-gray-400 flex justify-center text-xs md:text-base">
    created by
    <a href="https://devchallenges.io/portfolio/siamtbhuiyan" class="font-bold"
      >@siamtbhuiyan</a
    >
    - devChallenges
  </div>
</template>

// Front-end Developer/search-jobs/src/components/Footer.jsx
const Footer = () => {
    return (
      <>
        <p className="text-gray-400 mx-auto pb-3 text-center text-xs sm:text-base">
          created by{" "}
          <a
            href="https://github.com/siamtbhuiyan"
            className="font-bold"
          >
            @siamtbhuiyan
          </a>{" "}
          - devChallenges
        </p>
      </>
    );
  };
  
  export default Footer;
